[tox]
envlist = py{310,311,312,313}

[pytest]
python_classes = *Tests *TestCase *Test
log_level = INFO

[testenv]
deps=pytest
     blessings
     PyHamcrest
     configobj
     commodity
     doublex
passenv = TERM
          SHELL
          HOME
          PYTHONPATH
commands=pytest test
